export type EthicalPerspective = 'UTILITARIANISM' | 'DEONTOLOGY' | 'VIRTUE_ETHICS' | 'JUSTICE' | 'CARE_ETHICS';

export interface Choice {
  id: string;
  text: string;
  perspective: EthicalPerspective;
  consequenceSummary: string;
}

export interface Scenario {
  id: string;
  title: string;
  category: 'AUTONOMOUS_VEHICLE' | 'MEDICAL_AI' | 'JUDICIAL_AI' | 'RECRUITMENT_AI';
  difficulty: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  description: string;
  imageUrl: string;
  choices: Choice[];
  learningPoints: string[];
}

export interface SimulationResult {
  scenarioId: string;
  choiceId: string;
  analysis?: string; // Generated by Gemini
  discussionQuestions?: string[]; // Generated by Gemini
  timestamp: number;
}

export interface UserStats {
  scenariosCompleted: number;
  perspectiveCounts: Record<EthicalPerspective, number>;
  level: number;
  badges: string[];
}